### ISSUE TITLE
Kotlin 1.3.50 throws JVM Error when using JAR from Maven Central

### ISSUE THREAD

**Issue by woitee** [PvdBerg1998/HashKode#3]
When adding the Jar into dependencies, e.g. by this Gradle:

```
dependencies {
      implementation("com.github.pvdberg1998:hashkode:1.2.3")
}
```
or by putting it as a file by hand.

throws the following error:

**e: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: wrong bytecode generated**

_-- Followed by a bunch of bytecode  --_

Tried on several computers, and always ended up with this error.
Compiling the sources by hand works well, and the error only occurs in version 1.2.3 of hashkode.

**Comment by gabrielshanahan** [comment]
**Workaround:** I [forked](https://github.com/gabriel-shanahan/HashKode) the project and added Graddle configuration files, so you can use it as a [source dependency](https://blog.gradle.org/introducing-source-dependencies).

In build.gradle.kts:

```
dependencies {
    implementation("com.github.gabriel-shanahan:hashkode:latest.integration")
}
```

in settings.graddle.kts:
```
sourceControl {
    gitRepository(uri("https://github.com/gabriel-shanahan/HashKode.git")) {
        producesModule("com.github.gabriel-shanahan:hashkode")
    }
}
```

**Comment by PvdBerg1998** [comment]
That's a weird error. Any idea what caused it? Sorry for the slow response, I'm not maintaining this anymore. I'll accept a PR to fix it but I think I lost my private key to publish to maven :sweat_smile:

**Comment by gabrielshanahan** [comment]
Well, as per the error message, the bytecode is wrong - maybe built on a different Kotlin version, or for a different JVM version? We tried changing the version and the error started appearing only after a certain point, IIRC between 1.0 and 1.1 or 1.1 and 1.2. In any case, if you include the source in your project project and build them together, everything works fine - that's basically what my workaround is doing. The downside is that you have to build it every time.

There's nothing to PR except for the settings that allow the repo to be used as a Graddle source, which doesn't solve the problem. I think all that needs to be done is just rebuild the stuff on maven and that should solve it.

**Comment by gabrielshanahan** [comment]
So I ended up making my own library that is inspired by HashKode, with similar capabilities, if anyone runs into the same problem: https://github.com/gabrielshanahan/moroccode.

@PvdBerg1998 Pim, feel free to check it out, I'm actually pretty pleased with the result. I'd love your feedback, if you have time to give it.

**Comment by PvdBerg1998** [comment]
@gabrielshanahan Looks good! Happy to know my library was useful for someone. If you're still using any of my code, I'd like you to include my name in the license, as is required by the MIT license: https://opensource.stackexchange.com/questions/2391/how-should-i-assert-copyright-when-im-forking-an-mit-project . Thanks for the update, I'll close this issue and link to your library in the readme.

Edit: I'm not sure you are, your code looks quite different. You already gave credit in your readme aswell so that's cool too.

**Comment by gabrielshanahan** [comment]
I wrote the code from scratch, it was an interesting challenge, so it's all original. I just kept the capabilities the same, so one could be used in place of the other.
